#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
chown <user> /var/www/html/index
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
