#!/usr/bin/env bash
#this script install nginx server

sudo apt-get -y update
sudo apt-get install -y nginx nginx-common nginx-core
new_location='\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'
sed -i "/server_name _;/ a \ $new_location" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart