#!/usr/bin/env bash

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'

new_config="
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /404.html;
        location /404.html {
                internal;
                root /var/www/html;
                add_header Content-Type text/html;
        }
}
"

echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "$new_config" > /etc/nginx/sites-available/default

if [ "$(pgrep nginx | wc -l)" -gt 0 ];
then
    service nginx restart
else
    service nginx start
fi;
